### ISSUE TITLE
get_associated_bss crash

### ISSUE THREAD

**Issue by tahnok** [svinota/pyroute2#1469]
## Problem

When calling `iw.get_associated_bss(IF_INDEX)` I get an exception. `TypeError: 'async for' requires an object with __aiter__ method, got coroutine`

## Context

Version: `0.9.5`
Python version: `3.13.7`
OS: Ubuntu 25.10
Kernel: `6.17.0-14`

## Reproduction

```
>>> from pyroute2 import IW
>>> import socket
>>> socket.if_nametoindex("wlp1s0")
2
>>> with IW() as iw:
...     iw.get_associated_bss(2)
...     
Traceback (most recent call last):
  File "/home/wes/src/yslow/.venv/lib/python3.13/site-packages/pyroute2/iwutil.py", line 537, in get_associated_bss
    async for x in coro:
                   ^^^^
TypeError: 'async for' requires an object with __aiter__ method, got coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-3>", line 2, in <module>
    iw.get_associated_bss(2)
    ~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/wes/src/yslow/.venv/lib/python3.13/site-packages/pyroute2/iwutil.py", line 772, in get_associated_bss
    return self._run_with_cleanup(
           ~~~~~~~~~~~~~~~~~~~~~~^
        self.asyncore.get_associated_bss, ifindex
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/wes/src/yslow/.venv/lib/python3.13/site-packages/pyroute2/netlink/core.py", line 813, in _run_with_cleanup
    return self.asyncore.event_loop.run_until_complete(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        func(*argv, **kwarg)
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/wes/src/yslow/.venv/lib/python3.13/site-packages/pyroute2/iwutil.py", line 547, in get_associated_bss
    await coro.aclose()
          ^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'aclose'. Did you mean: 'close'?
```

**Comment by HarHarLinks** [comment]
same here: Python 3.14.4, Arch Linux, pyroute2 0.9.6.

bisecting on releases says it first stopped working in 0.9.3 (with a different error) and this specific error in 0.9.4.
