### ISSUE TITLE
wireguard: getting attributes of wg iface no longer working

### ISSUE THREAD

**Issue by cveilleux** [svinota/pyroute2#1021]
Tested with the latest release (`0.7.3`).

Adapted example straight from the documentation at https://docs.pyroute2.org/wireguard.html : 

```python
from pyroute2 import WireGuard
wg = WireGuard()
wg.info("wg0")[0].WGDEVICE_A_PRIVATE_KEY.value
```

Gives error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'wgmsg' object has no attribute 'WGDEVICE_A_PRIVATE_KEY'
```

I tested with many pyroute2 versions, and I have been able to pinpoint the exact release that broke the wireguard module: `0.5.15`

The above code works on `0.5.14` and same code crashes with `0.5.15`.

That release seems to contain multiple refactorings. There does not seem to be any change to the wireguard module itself, so I suspect some refactoring broke the wireguard support.

**Comment by svinota** [comment]
Ah! That's an error in the documentation; will be fixed tonight, many thanks for reporting

**Comment by cveilleux** [comment]
Thanks for the quick reply.

Right now, I am struggling to find the proper syntax.

I managed to get the attributes as a list of tuples and to convert it to a proper dict using this code:

```
attrs = wg.info("wg0")[0].get("attrs")
attrs_dict = {i[0]: i[1] for i in attrs}
private_key = attrs_dict["WGDEVICE_A_PRIVATE_KEY"]
```

I will wait for the updated doc.

Thanks

**Comment by svinota** [comment]
So the correct API is:

```python
from pyroute2 import WireGuard
wg = WireGuard()
wg.info("wg0")[0].get("WGDEVICE_A_PRIVATE_KEY")
```

PR: https://github.com/svinota/pyroute2/pull/1022

The updated docs will be on the site shortly.

**Comment by cveilleux** [comment]
I've updated my code using the newly documented syntax and everything works! Many thanks!

**Comment by svinota** [comment]
Thanks!
